### ISSUE TITLE
Supporting CoffeeScript?

### ISSUE THREAD

**Issue by trnc-ck** [karthikv/nodefront#1]
nodefront would be perfect if it would automatically complie coffeescript in .js files. any chance you could implement this?

thanks!

**Comment by mauricirododendro** [comment]
Can i ask you how can install nodefront on my pc?
I tried to follow hint: 
npm install -g nodefront
 but I have error
Thank you very much

**Comment by karthikv** [comment]
@clemenskroell It seems like there's quite a bit of demand for this and it shouldn't be difficult to implement. I'll get on it soon.

@mauricirododendro Do you have npm https://npmjs.org/ installed? What is the error you're getting? Could you direct any future comments to a different issue or to my email at me@karthikv.net? Thanks.

**Comment by federicoweber** [comment]
I will also appreciate coffeescript support.

thanks.

**Comment by karthikv** [comment]
CoffeeScript support has been added and version 0.0.4 has been released.
