### ISSUE TITLE
Version of q

### ISSUE THREAD

**Issue by ForbesLindesay** [karthikv/nodefront#15]
Would be good if we could update `q` and keep it up to date.  It should be perfectly backwards compatible at the moment and has some nice improvements.  I think we should generally move towards `0.8.x` for this, at least for now as it's better for development if we're always using the latest.  I usually just go for `*` for devDependencies unless there's a good reason not to?

**Comment by karthikv** [comment]
I wouldn't mind switching these to #.x.x (where # is the current major version number). In this way, we'd be less prone to major, breaking changes.

**Comment by karthikv** [comment]
I have taken care of this in the commit above.
