### ISSUE TITLE
Compile options?

### ISSUE THREAD

**Issue by trnc-ck** [karthikv/nodefront#21]
hey,

it would be cool to set some compile options, e.g. the 'pretty' attribute for keeping whitespace when compiling jade... 

maybe adding a config.json file where these options can be set?

thanks!

**Comment by ForbesLindesay** [comment]
I'm currently working on sorting out exactly this feature.  Expect it to be released within a week or so if all goes well.

**Comment by karthikv** [comment]
I've added this feature in via the commit above. It'll be released in version 1.0.0, which should be fully available next week. Let me know if you'd prefer to use it now and I can give you some instructions on how to get a pre-release set up on your system.

I'm closing this issue, but don't hesitate to comment.

**Comment by trnc-ck** [comment]
nice one, thanks. i'll wait till next week!

Am 28.08.2012 um 07:19 schrieb Karthik Viswanathan notifications@github.com:

**Comment by trnc-ck** [comment]
any news on this?

**Comment by karthikv** [comment]
I apologize for the delay; I've just released version 1.0.0, which adds in support for compile options. See https://github.com/karthikv/nodefront#configuration-files for documentation.

Let me know if you experience any issues and I'll get on it!

**Comment by notslang** [comment]
In the config file, shouldn't you specify what compiler the options are going to be passed to? So support for more compilers can be added, allowing different options to be passed to each one.

So the file could look like:

```
{
    "jade": {
        "pretty": true
    },
    "coffee-script": {
        "compress": true
    },
    "stylus": {
        "inline": true
    }
}
```

**Comment by karthikv** [comment]
Ah, yes, you make a good point. I'll reopen this issue and let you know when I've addressed it.

**Comment by karthikv** [comment]
Version 1.0.1, which was just released, adds support for extension-specific compiler options. See https://github.com/karthikv/nodefront#configuration-files.
