### ISSUE TITLE
Can I compile into another directory?

### ISSUE THREAD

**Issue by ghost** [karthikv/nodefront#25]
Can I compile jade and styl files into a different directory from where they are located? e.g. If I keep stylus files under /assets/styl, I would like them to be compiled into /public/css etc.

**Comment by notslang** [comment]
+1 this would be a great feature
...like if an `output-dir` option could be passed to specify a directory to output to (defaulting to the same directory as the source files if it is not specified)

**Comment by karthikv** [comment]
This is currently unsupported, but it is the next action item on my list. I'll let you know when it is implemented and released.

**Comment by gavinmcfarland** [comment]
Yep, this would be great. +1

**Comment by karthikv** [comment]
Version 1.0.1, which was just released, adds support for compiling into another directory by means of the `-o/--output` option. See https://github.com/karthikv/nodefront#options.

**Comment by ghost** [comment]
This is great!

**Comment by ForbesLindesay** [comment]
:+1:
