### ISSUE TITLE
using old versions of modules

### ISSUE THREAD

**Issue by notslang** [karthikv/nodefront#27]
Nodefront installs with jade `0.26.3` (which is an old version). The current version is `0.27.6`. This should be an easy fix by changing `package.json` to just require a version of jade that is `>= 0.26.3`, rather than restricting jade to be within `0.26.X`.

**Comment by notslang** [comment]
...also using an old version of stylus

**Comment by karthikv** [comment]
Thanks for pointing this out; I've allowed for the latest versions of jade/stylus/coffee-script as per your suggestion. This has been released in version 1.0.6. Let me know if you continue to experience issues.
