### ISSUE TITLE
Prevent Jade embedded in script tag from compilation? (Contains simple workaround)

### ISSUE THREAD

**Issue by JogoShugh** [karthikv/nodefront#32]
I'm not sure really if this is an issue or not, but thought I'd describe it and my workaround:
## Goal

My goal is to have index.jade on my local machine where I can write code in Jade, then compile it to HTML for including in a mobile app that will run offline without Node serving it.

But, I also want to use Jade templates locally in the client. I achieved that using the jquery.jade plugin available on GitHub.
## Code

Thus, I hade a bunch of jade elements inside "body", then after body I had a template with embedded jade:

``` jade
script(id="challengeCompletedDetailsTemplate", type="text/x-jade")
    div.challengeCompletedDetails
        ul(data-role="listview", data-inset="true", data-theme="e")
            li(data-role="list-divider") #{name} review
            etc etc etc...
```
## Compilation Issue

But, when I compiled with nodefront, I got this kind of cryptic error:

```
    205|     #settings.ui-corner-all(data-role='dialog')
    206|       a.ui-btn-right(href='#', data-rel='back', data-role='button', dat
a-icon='delete', data-iconpos='notext') Close
  > 207|       div(style='padding: 10px 20px;') ...Settings...
    208|
    209|     #messageDialog(data-role='dialog', data-transition='flip')
    210|       div(data-role='header')

name is not defined
```

There is no "name" inside of that part, at line 207, code that sat just above the template code.

But, name is a variable that I pass into the template dynamically, as seen in `#{name} review` in the template snippet above.
## Workaround

My workaround was to put it into an external file and give it a different extension:

``` jade
script(id="challengeCompletedDetailsTemplate", type="text/x-jade", src="challengeCompletedDetailsTemplate.jadeT")
```

(This is probably a better practice anyway, of having an external, small file for the view than embedding it into the index.)

**Comment by ForbesLindesay** [comment]
Jade templates can be pre-compiled into a JavaScript function, I'd recommend you do that at build time as it will result in much better performance on the clients.

**Comment by ForbesLindesay** [comment]
Either way, if you want a better solution to this problem (or to publicise your workaround) you should create an issue in the [jade repositoriry](https://github.com/visionmedia/jade) as this has nothing specifically to do with nodefront and everything to do with jade.
