### ISSUE TITLE
ERROR with js-yaml @ nodefront installation

### ISSUE THREAD

**Issue by rokf** [karthikv/nodefront#38]
I am getting some kind of error with <b>js-yaml</b> at the installation of nodefront. Any ideas?

<b>sudo npm install -g nodefront</b> results in:

Error: ENOENT, chmod '/usr/local/lib/node_modules/nodefront/node_modules/commander-config/node_modules/js-yaml/bin/js-yaml.js'

My node version is <b>v0.10.1</b> and my npm version is <b>1.2.15</b>

<b>error</b> path /usr/local/lib/node_modules/nodefront/node_modules/commander-config/node_modules/js-yaml/bin/js-yaml.js
<b>error</b> code ENOENT
<b>error</b> errno 34

**Comment by rokf** [comment]
Solved just now :smile: 
Was some kind of <b>npm</b> error like it seems.

Did it like this:

<b>Remove the yaml directory:</b>
$ sudo rm -rf ~/.npm/js-yaml

<b>And clear the cache:</b>
$ sudo npm cache clear

<b>And then:</b> sudo npm install -g nodefront

Worked like a charm!

**Comment by karthikv** [comment]
Good to hear! I'll keep your solution in mind if others run into the issue.
