### ISSUE TITLE
Error while minify recursively

### ISSUE THREAD

**Issue by Somebi** [karthikv/nodefront#41]
root@mydomain:/# nodefront minify /home/cms/mydomain/public/test/

Automatically adding recursive option because file target looks to be in another directory.

/usr/local/lib/node_modules/nodefront/node_modules/q/q.js:1440
                throw error;
                      ^
Error: ENOENT, stat '/dev/core'

**Comment by Somebi** [comment]
As i understand from the context. q.js is a module RCP like, to communicate with nodefront. But it's requesting /dev/core which i doesn't have on my Ubuntu. What is /dev/core?

**Comment by Somebi** [comment]
Oh actually it's there, that's the symlink to /proc/kcore . But it seems /proc/kcore is missing. o_O

**Comment by Somebi** [comment]
Hmm it seems it's a link to physical memory, through which communication i going on?

**Comment by Somebi** [comment]
There is no /proc/kcore on my system. 
Using:
Distributor ID: Ubuntu
Description:    Ubuntu 12.10
Release:        12.10
Codename:       quantal

**Comment by karthikv** [comment]
Don't run minify from your root directory. Nodefront detected that the file you wanted to minify was in a subdirectory, and added the recursive option, meaning that it will search all files in your root directory for those that match the regular expression "/home/cms/mydomain/public/test/".

Instead, cd to the "/home/cms/mydomain/public/test/" directory and just run `nodefront minify -rcji` to minify all CSS, JavaScript, and images recursively. Take a look at the [minify command documentation](https://github.com/karthikv/nodefront#minify-command) for more details. Reopen this issue if you continue to experience problems.

**Comment by Somebi** [comment]
So nodefront support only "current directory" feature? No absolute paths? Only relative? I'm confused.

**Comment by Somebi** [comment]
So if i have javascript files in another folder and images too, i have to run spawn two more processes instead of one. Sounds unreasonable...

**Comment by Somebi** [comment]
But anyway, thanks for your great tool. Saved me some time. Wanted to start writting something myself. Probably will fork later. ;)

**Comment by ForbesLindesay** [comment]
Just use paths relative to the root of your project, not the root of your hard drive/computer.  Then run nodefront in the root of your project.  Absolute paths for things like this are generally an anti-pattern as they make code less portable (It can't easily be moved from one folder/computer to another)

**Comment by Somebi** [comment]
Ok ok, didn't knew such specifics.

**Comment by ForbesLindesay** [comment]
This is true of how most command line tools work :smile:
