### ISSUE TITLE
system resources

### ISSUE THREAD

**Issue by tborychowski** [karthikv/nodefront#42]
I'm experiencing a lot of resource usage on windows:
![2013-08-21_173047](https://f.cloud.github.com/assets/392513/1002585/1cd888f0-0a7f-11e3-8c12-0462607c8c9c.png)
It constantly oscillates around 20-24% (and it's a quad core dell).
 The command is:

```
nodefront serve -l
```

Might that be due to a huge number of files in the particular folder (around 1400)?
(the folder also contains node_modules)

**Comment by karthikv** [comment]
What command are you running, and how many files are in your folder?

**Comment by tborychowski** [comment]
Sorry, forgot to mention. The command is:

```
nodefront serve -l
```

and there are around 1400 files (including node_modules)

**Comment by karthikv** [comment]
If you're using the `serve` command without any options, then I don't see why it's taking up so much CPU. We're simply using the built-in `http.createServer()` function that node provides. Furthermore, we're only reading files on an on-demand basis when a request is made, so it shouldn't matter how many there are. Can you try seeing how much CPU a hello world server (such as the one on the node.js front page) consumes?

**Comment by tborychowski** [comment]
Hi karthikv,
The node test server (the one from the homepage) uses almost no resources (no processor and some 14MB ram).

However I've done some more testing and it seems that the huge load is caused by the `-l` parameter. 
- If I run only `nodefront serve` it is the same as the demo server (almost no resources)
- If I run `nodefront serve -l` it get's heavy (sorry that I've missed the switch in earlier posts)

Moreover, the load apparently depends on the number of files - in small projects (with a <10 files) the load is almost negligible, with large ones - it gets to 20-30%.

**Comment by karthikv** [comment]
Yes, the -l option has to monitor all files in the current directory for modifications. If you have 1400 files, it's definitely going to use a decent amount of CPU and RAM.

```
I don't think there's much we can do about this. Perhaps we could look for a library that monitors files more efficiently, but nodefront really isn't tailored to serving large projects anyway.
```

**Comment by tborychowski** [comment]
The project itself is very small (10 files) but it uses grunt to build js/less and grunt requires node_modules...
Would it be possible to exclude node_modules from monitoring? That would probably solve more issues (e.g. #26).

**Comment by karthikv** [comment]
Is it possible to simply move the files you'd like to serve into a separate directory where node_modules is not present? Alternatively, you can move node_modules up one directory and you'll still have access to grunt without the file bloat.

**Comment by tborychowski** [comment]
Currently grunt doesn't allow node_modules from a different path (or parent folder), so no, it's not simple, but achievable (I'd need to move all files to a child dir, except node_modules, gruntfile.js and package.json and then update paths gruntfile.js). 

As I'd have to do this for a dozen of small projects, I think I'll just stick to hitting `F5` instead and not use `-l` switch...
