### ISSUE TITLE
nodefront doesn't do anything when you run it with no options

### ISSUE THREAD

**Issue by ForbesLindesay** [karthikv/nodefront#7]
As far as I'm aware, running `nodefront` with no options or command does nothing.  If that's the case, it would be useful if it could be equivalent to running `nodefront -h`

**Comment by ForbesLindesay** [comment]
Also running `nodefront compile -h` prints `error: option '-h, --hostname <hostname>' argument missing` rather than printing help because the two command options clash.  I'd say either hostname should be re-named, or we should detect when -h is the only option and has no arguments.

**Comment by karthikv** [comment]
Yes, I agree. I'll get these two fixed up later today.

**Comment by ForbesLindesay** [comment]
Thanks

**Comment by karthikv** [comment]
These two issues have been solved in version 0.0.8, which was just released.
