### ISSUE TITLE
nodefront doesn't serve index.html files

### ISSUE THREAD

**Issue by ForbesLindesay** [karthikv/nodefront#8]
It would be useful if nodefront served index.html files by default in the normal location.

**Comment by karthikv** [comment]
Do you mean visiting `http://localhost:3000/some/directory/` should serve `http://localhost:3000/some/directory/index.html`? If so, you make a good point; I'll fix this up soon as well.

**Comment by ForbesLindesay** [comment]
Indeed, that's exactly what I meant :)

**Comment by karthikv** [comment]
This issue has been solved in version 0.0.8, which was just released.
