### ISSUE TITLE
Markdown in Jade doesn't work

### ISSUE THREAD

**Issue by ForbesLindesay** [karthikv/nodefront#9]
Can you support using `marked` with the markdown filter on `jade`.  If you add it to dependencies that should be sufficient.

**Comment by ForbesLindesay** [comment]
Ah, it does if you do `npm install -g marked` first, perhaps a note in the docs then?

**Comment by karthikv** [comment]
I'm not sure whether `marked` should be included by default with nodefront; I think adding that note to the docs would be a better option for those who need markdown support.

**Comment by ForbesLindesay** [comment]
Agreed, a note in the docs would be good for me.

**Comment by karthikv** [comment]
This issue has been solved in version 0.0.8, which was just released.
